packages:
  - playground
  - docs

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - vue-demi


overrides:
  "@nuxt/kit": "^4.1.2"
  "@nuxt/schema": "4.3.1"
  "@nuxtjs/ionic": "link:."
  consola: "^3.4.2"
  nuxt-component-meta: ">=0.14.0"
